In [2]:
!pip install --upgrade pip

Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (25.1)
Collecting pip
  Downloading pip-25.2-py3-none-any.whl.metadata (4.7 kB)
Downloading pip-25.2-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 21.2 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.1
    Uninstalling pip-25.1:
      Successfully uninstalled pip-25.1
Successfully installed pip-25.2

In [3]:
!pip3 install pandas fastparquet

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.1.4)
Requirement already satisfied: fastparquet in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2024.11.0)
Requirement already satisfied: numpy<2,>=1.23.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (1.26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas) (2023.4)
Requirement already satisfied: cramjam>=2.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from fastparquet) (2024.9.0)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from fastparquet) (23.1)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [4]:
!pip3 install huggingface_hub

Collecting huggingface_hub
  Downloading huggingface_hub-0.35.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface_hub) (3.16.1)
Requirement already satisfied: fsspec>=2023.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface_hub) (2024.9.0)
Requirement already satisfied: packaging>=20.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface_hub) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface_hub) (6.0.1)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface_hub) (2.31.0)
Requirement already satisfied: tqdm>=4.42.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface_hub) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface_hub) (4.12.2)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface_hub)
  Downloading hf_xet-1.1.10-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.7 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface_hub) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface_hub) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface_hub) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->huggingface_hub) (2023.7.22)
Downloading huggingface_hub-0.35.0-py3-none-any.whl (563 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 563.4/563.4 kB 14.9 MB/s  0:00:00
Downloading hf_xet-1.1.10-cp37-abi3-macosx_11_0_arm64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 22.9 MB/s  0:00:00
Installing collected packages: hf-xet, huggingface_hub
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [huggingface_hub]1/2 [huggingface_hub]
Successfully installed hf-xet-1.1.10 huggingface_hub-0.35.0

In [5]:
import pandas as pd

splits = {'train': 'train.parquet', 'validation': 'validation.parquet'}
df_train = pd.read_parquet("hf://datasets/coastalcph/tydi_xor_rc/" + splits["train"], engine='fastparquet')
df_val = pd.read_parquet("hf://datasets/coastalcph/tydi_xor_rc/" + splits["validation"], engine='fastparquet')
print(f"Train size: {len(df_train)}, Validation size: {len(df_val)}")

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Train size: 15343, Validation size: 3011

In [6]:
df_train.head()

,question,context,lang,answerable,answer_start,answer,answer_inlang
0,উইকিলিকস কত সালে সর্বপ্রথম ইন্টারনেটে প্রথম তথ...,WikiLeaks () is an international non-profit or...,bn,True,182,2006,None
1,দ্বিতীয় বিশ্বযুদ্ধে কোন দেশ পরাজিত হয় ?,The war in Europe concluded with an invasion o...,bn,True,48,Germany,None
2,মার্কিন যুক্তরাষ্ট্রের সংবিধান অনুযায়ী মার্কিন...,Same-sex marriage in the United States expande...,bn,False,-1,no,None
3,আরব-ইসরায়েলি যুদ্ধে আরবের মোট কয়জন সৈন্যের মৃ...,The exact number of Arab casualties is unknown...,bn,True,39,unknown,None
4,বিশ্বে প্রথম পুঁজিবাদী সমাজ কবে গড়ে ওঠে ?,"As Thomas Hall (2000) notes, ""The Sung Empire ...",bn,True,1219,17th century,None

In [7]:
# Split train and validation into ar, ko and te based on the lang column
df_ar_train = df_train[df_train['lang'] == 'ar']
df_ko_train = df_train[df_train['lang'] == 'ko']
df_te_train = df_train[df_train['lang'] == 'te']

df_ar_val = df_val[df_val['lang'] == 'ar']
df_ko_val = df_val[df_val['lang'] == 'ko']
df_te_val = df_val[df_val['lang'] == 'te']

print(f"Arabic train size: {len(df_ar_train)}, validation size: {len(df_ar_val)}")
print(f"Korean train size: {len(df_ko_train)}, validation size: {len(df_ko_val)}")
print(f"Telugu train size: {len(df_te_train)}, validation size: {len(df_te_val)}")

Arabic train size: 2558, validation size: 415
Korean train size: 2422, validation size: 356
Telugu train size: 1355, validation size: 384

In [8]:
# Print the first row of each dataframe
print("Arabic train first row:")
print(df_ar_train.iloc[0])
print("\nKorean train first row:")
print(df_ko_train.iloc[0])
print("\nTelugu train first row:")
print(df_te_train.iloc[0])

Arabic train first row:
question                متى تدخلت روسيا في  الحرب الأهلية السورية؟
context          The Russian military intervention in the Syria...
lang                                                            ar
answerable                                                    True
answer_start                                                    67
answer                                              September 2015
answer_inlang                                                 None
Name: 11213, dtype: object

Korean train first row:
question                                         30년 전쟁의 승자는 누구인가?
context          The conflict between France and Spain continue...
lang                                                            ko
answerable                                                    True
answer_start                                                    21
answer                                                      France
answer_inlang                                                 None
Name: 4792, dtype: object

Telugu train first row:
question         ప్రపంచంలో  మొట్టమొదటి దూర విద్య విద్యాలయం ఏ దే...
context          Referred to as "People's University" by Charle...
lang                                                            te
answerable                                                    True
answer_start                                                   236
answer                                                      London
answer_inlang                                                 None
Name: 13771, dtype: object

In [9]:
df_ar_train.iloc[3]['context']

'The 2014 Israel–Gaza conflict also known as Operation Protective Edge (, "Miv\'tza Tzuk Eitan", lit. "Operation Strong Cliff") and sometimes referred to as the 2014 Gaza war,\nwas a military operation launched by Israel on 8 July 2014 in the Hamas-ruled Gaza Strip. Following the kidnapping and murder of three Israeli teenagers by Hamas members, the IDF conducted "Operation Brother\'s Keeper" to arrest militant leaders, Hamas fired rockets into Israel and a seven-week conflict broke out. The Israeli airstrikes and ground bombardment, the Palestinian rocket attacks and the ground fighting resulted in the death of thousands of people, the vast majority of them Gazans.'

In [10]:
#When did Russia intervene in the Syrian civil war?
df_ar_train.iloc[0]['question']

'متى تدخلت روسيا في  الحرب الأهلية السورية؟'

In [11]:
df_ar_train.iloc[0]['context']

'The Russian military intervention in the Syrian Civil War began in September 2015, after an official request by the Syrian government for military aid against rebel and jihadist groups. The intervention initially consisted of air strikes fired by Russian aircraft stationed in the Khmeimim base at targets primarily in north-western Syria, against militant groups opposed to the Syrian government, including Syrian National Coalition, the Islamic State of Iraq and the Levant (ISIL), al-Nusra Front (al-Qaeda in the Levant) and the Army of Conquest. Besides, Russian military advisors and special operations forces were stationed in Syria. Prior to the intervention, Russian involvement in the Syrian Civil War had mainly consisted of supplying the Syrian Army. At the end of December 2017, Russia said its troops would be based in Syria permanently.'

In [12]:
#When did Hungary gain independence from Austria?
df_ar_train.iloc[1]['question']

'متى حصلت هنغاريا على استقلالها من النمسا ؟'

In [13]:
df_ar_train.iloc[1]['context']

'By 1918, the economic situation had deteriorated alarmingly in Austria-Hungary; strikes in factories were organized by leftist and pacifist movements, and uprisings in the army had become commonplace. In the capital cities of Vienna and Budapest, the Austrian and the Hungarian leftist liberal movements and their leaders supported the separatism of ethnic minorities. Austria-Hungary signed the Armistice of Villa Giusti in Padua on 3 November 1918. In October 1918, the personal union between Austria and Hungary was dissolved.'

In [14]:
#Is the Harry Potter series against Christian laws?
df_ar_train.iloc[4]['question']

'هل سلسلة هاري بوتر مخالفة لقوانين المسيحية ؟'

In [15]:
df_ar_train.iloc[4]['context']

'Religious debates over the "Harry Potter" series of books by J. K. Rowling are based on claims that the novels contain occult or Satanic subtexts. A number of Protestant, Catholic, and Orthodox Christians have argued against the series, as have some Shia and Sunni Muslims. Supporters of the series have said that the magic in "Harry Potter" bears little resemblance to occultism, being more in the vein of fairy tales such as "Cinderella" and "Snow White", or to the works of C. S. Lewis and J. R. R. Tolkien, both of whom are known for writing fantasy novels with Christian subtexts. Far from promoting a particular religion, some argue, the "Harry Potter" novels go out of their way to avoid discussing religion at all. However, the author of the series, J. K. Rowling, describes herself as a practising Christian, and many have noted the Christian references which she includes in the final novel "Harry Potter and the Deathly Hallows".'

In [16]:
df_ar_val.head()

,question,context,lang,answerable,answer_start,answer,answer_inlang
1411,ما هي أولى جامعات فنلندا؟,"The Royal Academy of Åbo ( or ""Åbo Kungliga Ak...",ar,True,4,Royal Academy of Åbo,None
1412,ما عدد الدول المطلة على بحر البلطيق؟,The Baltic Sea is a marginal sea of the Atlant...,ar,True,68,"Finland, Sweden, Denmark, Estonia, Latvia, Lit...",None
1413,اين عاش نيوتن؟,"From age 12 to age 17, Newton resided with Wil...",ar,True,74,Grantham,None
1417,هل زار ابن بطوطة اليمن؟,"After the ""hajj"" in either 1328 or 1330, he ma...",ar,False,-1,no,None
1422,من هو الرئيس الأول للجمهورية اليمنية؟,The first President of unified Yemen was Ali A...,ar,True,41,Ali Abdullah Saleh,None

In [17]:
!pip3 install scikit-learn

Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (1.5.2)
Requirement already satisfied: numpy>=1.19.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (1.26.0)
Requirement already satisfied: scipy>=1.6.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (1.13.0)
Requirement already satisfied: joblib>=1.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from scikit-learn) (3.5.0)

In [18]:
!pip3 install transformers

Collecting transformers
  Downloading transformers-4.56.1-py3-none-any.whl.metadata (42 kB)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (0.35.0)
Requirement already satisfied: numpy>=1.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (1.26.0)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (6.0.1)
Collecting regex!=2019.12.17 (from transformers)
  Downloading regex-2025.9.18-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (2.31.0)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.0-cp39-abi3-macosx_11_0_arm64.whl.metadata (6.8 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Downloading safetensors-0.6.2-cp38-abi3-macosx_11_0_arm64.whl.metadata (4.1 kB)
Requirement already satisfied: tqdm>=4.27 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2024.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.12.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.1.10)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (2.0.5)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers) (2023.7.22)
Downloading transformers-4.56.1-py3-none-any.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 25.1 MB/s  0:00:00 27.4 MB/s eta 0:00:01
Downloading tokenizers-0.22.0-cp39-abi3-macosx_11_0_arm64.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 25.0 MB/s  0:00:00
Downloading regex-2025.9.18-cp311-cp311-macosx_11_0_arm64.whl (286 kB)
Downloading safetensors-0.6.2-cp38-abi3-macosx_11_0_arm64.whl (432 kB)
Installing collected packages: safetensors, regex, tokenizers, transformers
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [transformers]0m 3/4 [transformers]
Successfully installed regex-2025.9.18 safetensors-0.6.2 tokenizers-0.22.0 transformers-4.56.1

In [38]:
!pip uninstall torch torchvision torchaudio -y

Found existing installation: torch 2.8.0
Uninstalling torch-2.8.0:
  Successfully uninstalled torch-2.8.0
Found existing installation: torchvision 0.20.1
Uninstalling torchvision-0.20.1:
  Successfully uninstalled torchvision-0.20.1
WARNING: Skipping torchaudio as it is not installed.

In [42]:
!pip3 install torch==2.8 torchvision

Requirement already satisfied: torch==2.8 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (2.8.0)
Collecting torchvision
  Downloading torchvision-0.23.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.1 kB)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch==2.8) (3.16.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch==2.8) (4.12.2)
Requirement already satisfied: sympy>=1.13.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch==2.8) (1.14.0)
Requirement already satisfied: networkx in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch==2.8) (3.3)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch==2.8) (3.1.2)
Requirement already satisfied: fsspec in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch==2.8) (2024.9.0)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torchvision) (1.26.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torchvision) (11.1.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from sympy>=1.13.3->torch==2.8) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->torch==2.8) (2.1.3)
Downloading torchvision-0.23.0-cp311-cp311-macosx_11_0_arm64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 22.8 MB/s  0:00:00
Installing collected packages: torchvision
Successfully installed torchvision-0.23.0

In [43]:
import torch
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report
from transformers import pipeline
print(torch.__version__)

# --- Setup translation pipeline ---
# Load the Hugging Face NLLB model
translator = pipeline("translation", model="facebook/nllb-200-distilled-600M")

def translate_text(text: str, src_lang: str = "arb_Arab", tgt_lang: str = "eng_Latn") -> str:
    """
    Translate text from source to target language using NLLB.
    Default: Arabic -> English
    """
    if not isinstance(text, str) or text.strip() == "":
        return text
    result = translator(text, src_lang=src_lang, tgt_lang=tgt_lang, max_length=1024)
    return result[0]["translation_text"]

2.5.1

ValueError: Could not load model facebook/nllb-200-distilled-600M with any of the following classes: (<class 'transformers.models.auto.modeling_auto.AutoModelForSeq2SeqLM'>, <class 'transformers.models.auto.modeling_tf_auto.TFAutoModelForSeq2SeqLM'>, <class 'transformers.models.m2m_100.modeling_m2m_100.M2M100ForConditionalGeneration'>). See the original errors:

while loading with AutoModelForSeq2SeqLM, an error is thrown:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/pipelines/base.py", line 293, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 604, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 288, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5176, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5442, in _load_pretrained_model
    load_state_dict(checkpoint_files[0], map_location="meta", weights_only=weights_only).keys()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 532, in load_state_dict
    check_torch_load_is_safe()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1632, in check_torch_load_is_safe
    raise ValueError(
ValueError: Due to a serious vulnerability issue in `torch.load`, even with `weights_only=True`, we now require users to upgrade torch to at least v2.6 in order to use the function. This version restriction does not apply when loading files with safetensors.
See the vulnerability report here https://nvd.nist.gov/vuln/detail/CVE-2025-32434

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/pipelines/base.py", line 311, in infer_framework_load_model
    model = model_class.from_pretrained(model, **fp32_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 604, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 288, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5176, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5442, in _load_pretrained_model
    load_state_dict(checkpoint_files[0], map_location="meta", weights_only=weights_only).keys()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 532, in load_state_dict
    check_torch_load_is_safe()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1632, in check_torch_load_is_safe
    raise ValueError(
ValueError: Due to a serious vulnerability issue in `torch.load`, even with `weights_only=True`, we now require users to upgrade torch to at least v2.6 in order to use the function. This version restriction does not apply when loading files with safetensors.
See the vulnerability report here https://nvd.nist.gov/vuln/detail/CVE-2025-32434

while loading with TFAutoModelForSeq2SeqLM, an error is thrown:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/pipelines/base.py", line 293, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 607, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.m2m_100.configuration_m2m_100.M2M100Config'> for this kind of AutoModel: TFAutoModelForSeq2SeqLM.
Model type should be one of BartConfig, BlenderbotConfig, BlenderbotSmallConfig, EncoderDecoderConfig, LEDConfig, MarianConfig, MBartConfig, MT5Config, PegasusConfig, T5Config.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/pipelines/base.py", line 311, in infer_framework_load_model
    model = model_class.from_pretrained(model, **fp32_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 607, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.m2m_100.configuration_m2m_100.M2M100Config'> for this kind of AutoModel: TFAutoModelForSeq2SeqLM.
Model type should be one of BartConfig, BlenderbotConfig, BlenderbotSmallConfig, EncoderDecoderConfig, LEDConfig, MarianConfig, MBartConfig, MT5Config, PegasusConfig, T5Config.

while loading with M2M100ForConditionalGeneration, an error is thrown:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/pipelines/base.py", line 293, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 288, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5176, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5442, in _load_pretrained_model
    load_state_dict(checkpoint_files[0], map_location="meta", weights_only=weights_only).keys()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 532, in load_state_dict
    check_torch_load_is_safe()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1632, in check_torch_load_is_safe
    raise ValueError(
ValueError: Due to a serious vulnerability issue in `torch.load`, even with `weights_only=True`, we now require users to upgrade torch to at least v2.6 in order to use the function. This version restriction does not apply when loading files with safetensors.
See the vulnerability report here https://nvd.nist.gov/vuln/detail/CVE-2025-32434

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/pipelines/base.py", line 311, in infer_framework_load_model
    model = model_class.from_pretrained(model, **fp32_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 288, in _wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5176, in from_pretrained
    ) = cls._load_pretrained_model(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 5442, in _load_pretrained_model
    load_state_dict(checkpoint_files[0], map_location="meta", weights_only=weights_only).keys()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 532, in load_state_dict
    check_torch_load_is_safe()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/transformers/utils/import_utils.py", line 1632, in check_torch_load_is_safe
    raise ValueError(
ValueError: Due to a serious vulnerability issue in `torch.load`, even with `weights_only=True`, we now require users to upgrade torch to at least v2.6 in order to use the function. This version restriction does not apply when loading files with safetensors.
See the vulnerability report here https://nvd.nist.gov/vuln/detail/CVE-2025-32434

In [ ]:
# Interrogative words to look for (in English, since we translate)
INTERROGATIVES = {'who', 'what', 'when', 'where', 'why', 'how', 'which', 'whom'}

def is_answerable(row, translate=True, src_lang="arb_Arab"):
    # Extract fields
    question = str(row['question'])
    context = str(row['context'])

    # Optionally translate question/context to English
    if translate:
        question = translate_text(question, src_lang=src_lang, tgt_lang="eng_Latn")
        #context = translate_text(context, src_lang=src_lang, tgt_lang="eng_Latn")

    # Lowercase for matching
    question = question.lower()
    context = context.lower()

    # Rule 1: No word overlap
    question_words = set(question.split())
    context_words = set(context.split())
    if len(question_words.intersection(context_words)) == 0:
        return 0

    # Rule 2: No interrogative words
    if not any(word in question_words for word in INTERROGATIVES):
        return 0

    return 1

# --- Apply to your dataframes ---
train_df = df_ar_train
val_df = df_ar_val

# Apply to validation set (with translation)
val_df['predicted'] = val_df.apply(is_answerable, axis=1)

# Evaluate on validation
print("Validation Results:")
print(classification_report(val_df['answerable'], val_df['predicted']))

# Optional: Evaluate on training (uncomment if needed)
# train_df['predicted'] = train_df.apply(is_answerable, axis=1)
# print("\nTraining Results:")
# print(classification_report(train_df['answerable'], train_df['predicted']))

Device set to use cpu

Validation Results:
              precision    recall  f1-score   support

       False       0.60      0.96      0.74        52
        True       0.99      0.91      0.95       363

    accuracy                           0.92       415
   macro avg       0.80      0.94      0.85       415
weighted avg       0.94      0.92      0.92       415

/tmp/ipykernel_127341/1172023668.py:55: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  val_df['predicted'] = val_df.apply(is_answerable, axis=1)

In [23]:
(df_ar_val["answerable"] == True).sum(), (df_ar_val["answerable"] == False).sum()

(363, 52)

In [24]:
for i in range(150):
    question = df_ar_train.iloc[i]['question']
    question = translate_text(question, src_lang="arb_Arab", tgt_lang="eng_Latn")
    print(question)

NameError: name 'translate_text' is not defined